# Generated by Django 4.2.5 on 2023-09-21 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=None)),
                ('photo_basic', models.ImageField(blank=True, height_field='height_basic', null=True, upload_to=None)),
                ('photo_premium', models.ImageField(blank=True, height_field='height_premium', null=True, upload_to=None)),
                ('photo_active', models.ImageField(blank=True, null=True, upload_to=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('height_basic', models.IntegerField(default=200)),
                ('height_premium', models.IntegerField(default=400)),
                ('time_active', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
