# Generated by Django 4.2.5 on 2023-09-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='author',
            new_name='user',
        ),
    ]
